default: &default
  adapter:  postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: interview_homework_dev

test:
  <<: *default
  database: interview_homework_test